oe_link_lists.link_list_type.*:
  type: config_entity
  label: 'Link List type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string

field.value.link_list_configuration:
  type: mapping
  label: Default value
  mapping:
    value:
      type: label
      label: Value
