oe_link_lists.link_list_type.*:
  type: config_entity
  label: 'Link List type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    configurable_link_source_plugins:
      type: boolean
      label: 'Whether this bundle should allow to select link source plugins'
    default_link_source:
      type: string
      label: 'Whether this bundle works with only one link source, automatically configured on it'

field.value.link_list_configuration:
  type: mapping
  label: Default value
  mapping:
    value:
      type: label
      label: Value
