oe_link_lists_manual_source.link_list_link_type.*:
  type: config_entity
  label: 'Link List Link type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
